language: python

env:
    - CONDA="python=2.7"
    - CONDA="python=3.3"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --all --yes
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - travis_retry conda install --yes pytest

  # Build and install.
  - pushd conda-recipe
  - conda build .
  - yes | conda install `conda build . --output`
  - yes | conda install pytest
  - popd

script:
  - export TEST_CMD="py.test --ignore=notebook_examples"

  # Test with mpi4py.
  - ${TEST_CMD}
  - mpiexec -n 2 py.test -m mpi4py --ignore=notebook_examples

  # Test w/out mpi4py.
  - yes | conda remove mpi4py
  - ${TEST_CMD}

  # Test w/out GIS interoperability dependencies.
  - yes | conda remove shapely fiona rtree
  # Test flexible mesh can import w/out optionals.
  - py.test test/test_flexible_mesh/test_init.py::test_imports_required
  # Test UGrid w/out optional dependencies.
  - py.test --ignore=notebook_examples --ignore=test/test_flexible_mesh

notifications:
    irc: "chat.freenode.net#renci"