language: python

env:
  - CONDA_PYTHON_VERSION="2"
  - CONDA_PYTHON_VERSION="3"

# tdk: enable master when merged
branches:
  only:
    - flexible-mesh
#    - master

sudo: false

install:
  - if [[ "$CONDA_PYTHON_VERSION" == "2" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - yes | conda install conda-build jinja2
  - conda config --add channels nesii/channel/ocgis

  # Build and install.
  - pushd conda-recipe
  - conda build .
  - yes | conda install `conda build . --output`
  - yes | conda install pytest
  - popd

script:
  - export TEST_CMD="py.test --ignore=notebook_examples"

  # Test with mpi4py.
  - ${TEST_CMD}
  - mpiexec -n 2 py.test -m mpi4py --ignore=notebook_examples

  # Test w/out mpi4py.
  - yes | conda remove mpi4py
  - ${TEST_CMD}

  # Test w/out GIS interoperability dependencies.
  - yes | conda remove shapely fiona rtree
  # Test flexible mesh can import w/out optionals.
  - py.test test/test_flexible_mesh/test_init.py::test_imports_required
  # Test UGrid w/out optional dependencies.
  - py.test --ignore=notebook_examples --ignore=test/test_flexible_mesh

notifications:
    irc: "chat.freenode.net#renci"