sudo: false
language: python

env:
    - CONDA="python=2.7"
    - CONDA="python=3.3"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --all --yes
    - travis_retry conda create --yes -n test $CONDA --file requirements.txt
    - source activate test
    - travis_retry conda install --yes pytest

    # Create test environment for optional tests.

    # TODO: Once netCDF4 dependency issue solved with IOOS, change file to "requirements-optional.txt".
    - travis_retry conda create --yes -n test-optional $CONDA shapely fiona "libgdal<2" mpi4py netcdf4 matplotlib scipy
    - source activate test-optional
    # Workaround to avoid downgrading netCDF4.
    - conda install --yes -c ioos rtree
    - travis_retry conda install --yes pytest


install:
    - mkdir files

script:
    # Run tests ignoring test files using optional dependencies.
    - source activate test
    - py.test --ignore=notebook_examples --ignore=test/test_flexible_mesh

    # Run full test suite including optional dependencies.
    - source activate test-optional
    - py.test --ignore=notebook_examples
    # Run MPI tests.
    - mpiexec -n 2 py.test -m mpi4py --ignore=notebook_examples

notifications:
    irc: "chat.freenode.net#renci"
