# tdk: return version
package:
    name: pyugrid
    version: flexible_mesh
#    version: master
#    version: 0.1.6

# tdk: return to upstream
source:
    git_url: https://github.com/NESII/pyugrid
    git_tag: flexible-mesh
#    git_url: https://github.com/pyugrid/pyugrid
#    git_tag: 0.1.6
#    git_tag: master

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy
        - shapely
        - fiona
        - libgdal <2
        - mpi4py
        - rtree

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
