package:
    name: pyugrid
    version: {{environ['CBUILD_PYUGRID_VERSION']}}

source:
    git_url: {{environ['CBUILD_PYUGRID_GIT_URL']}}
    git_tag: {{environ['CBUILD_PYUGRID_TAG']}}

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4
        - scipy
        - shapely
        - fiona
        - libgdal <2
        - mpi4py
        - rtree

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
